<a href="https://colab.research.google.com/github/aditya10938/DataScience-Assignment/blob/main/Assignment3_datascience.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Create a numpy array starting from 2 till 50 with a stepsize of 3.

In [2]:
import numpy
array = numpy.arange(2,50,3)
print(array)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47]


##Accept two lists of 5 elements each from the user. Convert them to numpy arrays. Concatenate these arrays and print it. Also sort these arrays and print it.

In [4]:
a=numpy.array([int(input()) for i in range(5)])
b=numpy.array([int(input()) for i in range(5)])
print(numpy.sort(numpy.concatenate((a,b))))

1
2
3
4
5
6
7
8
9
10
[ 1  2  3  4  5  6  7  8  9 10]


##Write a code snippet to find the dimensions of a ndarray and its size

In [6]:
array=numpy.array([1,2,3,4,5,6,7,8])
print(array.ndim)
print(array.size)

1
8


##How to convert a 1D array into a 2D array? Demonstrate with the help of a code snippet Hint: np.newaxis, np.expand_dims

In [9]:
array= numpy.array([1,2,3,4,5,6])
t=array
t=t[:, numpy.newaxis]
print(t)
print(array)
t=array
print(t)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
[1 2 3 4 5 6]
[1 2 3 4 5 6]


##Consider two square numpy arrays. Stack them vertically and horizontally. Hint: Use vstack(), hstack()



In [11]:
a=numpy.array([[1,2,3],[4,5,6],[7,8,9]])
print(numpy.vstack(a))
print(numpy.hstack(a))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]


##How to get unique items and counts of unique items?

In [12]:
a=numpy.arange(1,10)
print(numpy.unique(a,return_counts=True))

(array([1, 2, 3, 4, 5, 6, 7, 8, 9]), array([1, 1, 1, 1, 1, 1, 1, 1, 1]))
